### ISSUE TITLE
Database download 

### ISSUE THREAD

**Issue by Rachine** [pyannote/pyannote-db-odessa-ami#7]
Hello,

For this db, are there subsets only to download, or everything has to be downloaded? 
Especially for the diarization pipeline, as used in the tutorial in pyannote.audio. 

Thank you very much! 

Best,

**Comment by hbredin** [comment]
`headset mix` audio recordings should be enough.

**Comment by Rachine** [comment]
Yes thank you! 

Just in case I put that here for other users and closing the issue:

files list can be found here : https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speaker_diarization#application 

and download here http://groups.inf.ed.ac.uk/ami/download/ with the corresponding spk list and headset mix option.

**Comment by hadware** [comment]
I've downloaded the full list of audio files (only for the headset mix recordings) just to be sure, since no subset of the files seemed to  work with pyannote.audio. Maybe you could specify which subset is needed (if there is one) in the Readme. I can also pull-request some modifications in the Readme if you can confirm that the full dataset is needed. Maybe I can also add the adequate download script generated by the Odessa website to this repo (in some way or another).

**Comment by hbredin** [comment]
The list of files can be inferred from [those files](https://github.com/pyannote/pyannote-db-odessa-ami/tree/master/AMI/data/speaker_diarization).

A pull request on `README.md` explaining how to download the dataset would be a great contribution. Thanks.

**Comment by hadware** [comment]
Alright, I'll aggregate the files cited in this directory to gather a list. 

I'll also add the corresponding download script to your repo (and the README.md will explain how to use it).

**Comment by hbredin** [comment]
While you are at it, also explain how to update `~/.pyannote/db.yml` accordingly :-D
For instance, the download script could print this explanation once download is finished.

**Comment by hadware** [comment]
![image](https://user-images.githubusercontent.com/5477031/52648319-99d8f880-2ee6-11e9-8ca3-7fa8ca95acc4.png)
